<?php
/**
 * @file
 * Social_gallery.module.
 */

include_once 'social_blog.features.inc';

/**
 * Implements hook_commons_bw_group_widget().
 */
function social_blog_commons_bw_group_widget() {
  return array(
    'commons_blogs' => array(
      'title' => 'Blogs',
      'type' => 'view',
      'vid' => 'blog',
      'display' => 'default',
      'bundle' => 'blog',
    ),
  );
}

/**
 * Implements hook_commons_entity_integration().
 */
function social_blog_commons_entity_integration() {
  return array(
    'node' => array(
      'blog' => array(),
    ),
  );
}

/**
 * Implements hook_strongarm_alter().
 */
function social_blog_strongarm_alter(&$items) {
  // Expose the Gallery content type for 'liking' via the Commons_like module
  // by altering the configuration for the Rate.module widget that it provides.
  if (!empty($items['rate_widgets']->value)) {
    foreach ($items['rate_widgets']->value as $key => $widget) {
      if ($widget->name == 'commons_like') {
        if (!in_array('gallery', $items['rate_widgets']->value[$key]->node_types)) {
          $items['rate_widgets']->value[$key]->node_types[] = 'blog';
        }
        if (!in_array('gallery', $items['rate_widgets']->value[$key]->comment_types)) {
          $items['rate_widgets']->value[$key]->comment_types[] = 'blog';
        }
      }
    }
  }
  // Expose the post content type for integration with Commons Radioactivity
  // and Commons Groups.
  foreach (array('commons_radioactivity_entity_types', 'commons_groups_entity_types') as $key) {
    if (isset($items[$key])) {
      $items[$key]->value['node']['blog'] = 1;
    }
  }
}

/**
 * Implements hook_views_default_views_alter().
 *
 * Display galleries on the browsing widget main view.
 */
function social_blog_views_default_views_alter(&$views) {
  if (!empty($views['commons_bw_all'])) {
    $views['commons_bw_all']->display['default']->display_options['filters']['type']['value']['blog'] = 'blog';
  }
}
