<?php

/**
 * @file
 * social_blocks.module
 */

/**
 * Implements hook_block_info().
 */
function social_blocks_block_info() {
  $blocks = array();
  $blocks['frontpage_banner'] = array(
    'info' => t('Frontpage banner'),
    'title' => 'Bliv en del af et aktivt online fællesskab',
  );
  $blocks['community_stats'] = array(
    'info' => t('Community statistics'),
    'title' => 'Bliv en del af et aktivt fællesskab',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function social_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'frontpage_banner':
      $block['content'] = social_blocks_frontpage_banner_view();
      break;

    case 'community_stats':
      $block['content'] = social_blocks_community_stats_view();
      break;
  }



  return $block;
}

/**
 * Implements hook_block_configure().
 */
function social_blocks_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'frontpage_banner':
      // Text field form element.
      $form['subtitle'] = array(
        '#type' => 'textfield',
        '#title' => t('Subtitle'),
        '#default_value' => variable_get('frontpage_banner_subtitle', '- Hat og briller '),
      );

      $form['subtitle2'] = array(
        '#type' => 'textfield',
        '#title' => t('Button text'),
        '#default_value' => variable_get('frontpage_banner_button_text', '- Bannerlink '),
      );

      $form['subtitle3'] = array(
        '#type' => 'textfield',
        '#title' => t('Button link'),
        '#default_value' => variable_get('frontpage_banner_button_link', '- Hat og briller '),
      );

      $form['subtitle4'] = array(
        '#type' => 'textfield',
        '#title' => t('Register'),
        '#default_value' => variable_get('frontpage_banner_register', '- Hat og briller '),
      );


      $form['file'] = array(
        '#name' => 'banner_image',
        '#type' => 'managed_file',
        '#title' => t('Choose an Image File'),
        '#description' => t('Select an Image for the custom block.  Only *.gif, *.png, *.jpg, and *.jpeg images allowed.'),
        '#default_value' => variable_get('banner_image_fid', ''),
        '#upload_location' => 'public://banner/',
        '#upload_validators' => array(
          'file_validate_extensions' => array('gif png jpg jpeg'),
        ),
      );
      break;

    case 'community_stats':
      // Text field form element.
      $form['subtitle'] = array(
        '#type' => 'textfield',
        '#title' => t('Subtitle'),
        '#default_value' => variable_get('community_stats_subtitle', ''),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function social_blocks_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'frontpage_banner':
      variable_set('frontpage_banner_subtitle', $edit['subtitle']);
      variable_set('frontpage_banner_button_text', $edit['subtitle2']);
      variable_set('frontpage_banner_button_link', $edit['subtitle3']);
      variable_set('frontpage_banner_register', $edit['subtitle4']);

      // Saving the file.
      if (isset($edit['file'])) {
        $file = file_load($edit['file']);
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
        $block = block_load('social_blocks', $delta);
        file_usage_add($file, 'social_blocks', 'block', $block->bid);
        variable_set('banner_image_fid', $file->fid);
      }
      else {
        variable_set('banner_image_fid', '');
      }
      break;

    case 'community_stats':
      variable_set('community_stats_subtitle', $edit['subtitle']);
      break;
  }
}

/**
 * Frontpage banner - block view.
 */
function social_blocks_frontpage_banner_view() {

  // Capture the image file path and form into HTML with attributes.
  $image_file = file_load(variable_get('banner_image_fid', ''));
  $image_path = '';

  if (isset($image_file->uri)) {
    $image_path = $image_file->uri;

    $image = theme('image_style', array(
          'style_name' => 'banner',
        'path' => $image_path,
        'alt' => '',
        'title' => '',
    ));
  }
  else {
    // Default image.
    $image_path = drupal_get_path("module", "social_blocks") . "/images/banner_default.jpg";

    $image = "<img src='" . url($image_path) . "' />";
  }

  $output = "";
  $output .= "<div class='subtitle'>" . variable_get('frontpage_banner_subtitle', '- Bliv en del af et online fællesskab') . "</div>";
  $output .= "<div class='banner-link'>" . l( variable_get('frontpage_banner_button_text', 'readmore'), variable_get('frontpage_banner_button_link', '/uset/register'), array('attributes' => array('class' => 'btn'))) . "</div>";
  $output .= "<div class='banner-register'>" . variable_get('frontpage_banner_register', 'register') . "</div>";
  $output .= render($image);

  return $output;
}

/**
 * Community stats - block view.
 */
function social_blocks_community_stats_view() {

  $output = "";
  $output .= "<div class='subtitle'>" . variable_get('community_stats_subtitle', '') . "</div>";
  $output .= "<div class='stats-top'>Dette community indeholder lige nu:</div>";
  $output .= "<div class='stats'>";
  $output .= "<div><span class='icon-bruger'></span> " . social_blocks_get_community_stats("members") . " brugere</div>";
  $output .= "<div><span class='icon-gruppe'></span> " . social_blocks_get_community_stats("groups") . " grupper</div>";
  $output .= "<div><span class='icon-indlaeg'></span> " . social_blocks_get_community_stats("posts") . " indlæg</div>";
  $output .= "</div>";
  $output .= "<div class='stats-link'>" . l(t('Create account'), 'user/register', array('attributes' => array('class' => 'btn'))) . "</div>";
  $output .= "<div class='stats-btm'>Det er <strong>gratis</strong> at oprette dig</div>";

  return $output;
}

/**
 * Get community stats.
 */
function social_blocks_get_community_stats($type) {

  switch ($type) {
    case "members":
      $query = new EntityFieldQuery();
      $query
        ->entityCondition('entity_type', 'user')
        ->propertyCondition('status', 1);
      $result = $query->count()->execute();
      break;

    case "groups":
      $query = new EntityFieldQuery();
      $query
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'group')
        ->propertyCondition('status', 1);
      $result = $query->count()->execute();
      break;

    case "posts":
      $query = new EntityFieldQuery();
      $query
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'post')
        ->propertyCondition('status', 1);
      $result = $query->count()->execute();
      break;
  }
  return (isset($result) ? $result : FALSE);
}
